# topics
key_frame_sub_topic: /kf
loop_pose_sub_topic: /loop_pose

key_frames_pub_topic: /back_end_kfs
frame_id: /map

# information matrix 
odom_info: [10, 10, 10, 10, 10, 10]
loop_pose_info: [10, 10, 10, 10, 10, 10]

# PGO Back End
save_pose: true
save_dir: "/home/adin/extra/slam_data/"
