#topics
kf_cloud_height_sub_topic: /kf_cloud_height
kf_image_sub_topic: /kf_image
kf_sub_topic: /kf
loop_pose_pub_topic: /loop_pose
frame_id: /map

save_loop_pose: true
save_dir: "/home/adin/extra/slam_data"

#semantic loop pose
loop_pose_step: 5
start_up_index: 60
index_exclude_range: 10
coarse_candidates: 10
#           background lane_line parking_line marker crossing vehicle bump stop_line
prior_size: [0.0, 0.0, 5000.0, 600.0, 400.0, 0.0, 2200.0, 400.0]
coarse_semantic_coeff: [0.0, 0.0, 1.0, 3.0, 5.0, 0.0, 5.0, 2.0]
fine_semantic_coeff: [0.0, 0.0, 0.05, 1.0, 1.0, 0.0, 5.0, 1.0]
coarse_similarity_limit: 0.95
fine_similarity_limit: 5.0

# icp
max_iteration: 20
fitness_upper_bound: 2.0


